# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_organization_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covenants',
            new_name='Covenant',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='noncomp_portfolio',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='pages.Organization'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='NoncompliantPortfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
