# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171031_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='pages.Organization'),
        ),
    ]
