# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20171031_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='covenant',
            name='indicator',
            field=models.CharField(choices=[('DSCR', 'Debt Service Coverage Ratio'), ('TOTAL_LIABILITIES', 'Total Liabilities'), ('CURRENT_RATIO', 'Current Ratio')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covenant',
            name='operator_options',
            field=models.CharField(choices=[('GREATER_THAN', '>'), ('LESS_THAN', '<'), ('EQUAL_TO', '='), ('NOT_EQUAL_TO', '≠')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_schedule',
            field=models.CharField(choices=[('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('QUARTERLY', 'quarterly'), ('SEMI-ANNUALLY', 'semi-annually'), ('ANNUALLY', 'annually')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covenant',
            name='cov_id',
            field=models.CharField(max_length=15),
        ),
    ]
