# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20171031_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covenant',
            name='date_last_compliant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='num_times_noncomp',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
