# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171031_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_headers', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('summarize_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='covenant',
            name='indicator',
            field=models.CharField(choices=[('DSCR', 'Debt Service Coverage Ratio'), ('TOTAL_LIABILITIES', 'Total Liabilities'), ('CURRENT_RATIO', 'Current Ratio')], max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pages.Statement'),
        ),
    ]
