# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 20:05
from __future__ import unicode_literals

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_app.models.post_upload_handler),
        ),
    ]
