# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_image',
            new_name='image',
        ),
    ]
